name: Deploy to Looker

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for all tags and branches

      - name: Get all tags
        id: get_tags
        run: echo "::set-output name=tags::$(git tag --sort=-v:refname)"

      - name: Check if new tag is the latest
        id: check_latest_tag
        run: |
          latest_tag=$(echo "${{ steps.get_tags.outputs.tags }}" | head -n 1)
          new_tag="${{ github.ref_name }}"
          if [ "$new_tag" != "$latest_tag" ]; then
            echo "New tag $new_tag is not the latest version. The latest is $latest_tag. Aborting deployment."
            exit 1
          fi
          echo "New tag $new_tag is the latest semantic version. Proceeding with deployment."

      - name: Trigger Looker Advanced Deploy
        env:
          LOOKER_WEBHOOK_SECRET: ${{ secrets.LOOKER_WEBHOOK_SECRET }}
        run: |
          curl -X POST \
            -H "X-Looker-Deploy-Secret: $LOOKER_WEBHOOK_SECRET" \
            "https://88aa1d94-1917-46df-bf19-8713411bc7de.looker.app/webhooks/projects/thelook_fabio/deploy/ref/${{ github.ref_name }}"
