name: CI

on: [push]

jobs:
  lams_job:
    runs-on: ubuntu-latest
    name: LAMS LookML Linter Job
    steps:
    - name: Checkout your LookML
      uses: actions/checkout@v4
      with:
        path: lookml-project
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '22.x'
    - name: Install LAMS
      #run: npm install -g @looker/look-at-me-sideways
      run: |
        git clone -b feat-gh-md https://github.com/looker-open-source/look-at-me-sideways.git
        cd look-at-me-sideways
        npm install
        npm link
        cd ..
    - name: Run LAMS
      # See [PRIVACY.md](https://github.com/looker-open-source/look-at-me-sideways/blob/master/PRIVACY.md)
      run: |
        cd lookml-project
        lams --reporting=no --input=**/*.lkml --output=github-job-summary
