name: CI

on: [push]

jobs:
  lams_job:
    runs-on: ubuntu-latest
    name: LAMS LookML Linter Job
    steps:
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '22.x'
    - name: Install LAMS
      #run: npm install -g @looker/look-at-me-sideways
      run: |
        pwd
        ORIGINAL_DIR=$(pwd)
        cd ~
        pwd
        git clone -b feat-gh-md https://github.com/looker-open-source/look-at-me-sideways.git
        cd look-at-me-sideways
        pwd
        npm install
        npm link
        cd "$ORIGINAL_DIR"
        pwd
    - name: Run LAMS
      # See [PRIVACY.md](https://github.com/looker-open-source/look-at-me-sideways/blob/master/PRIVACY.md)
      run: |
        pwd
        lams --reporting=no --output=github-job-summary
